FROM debian:bookworm-slim

ARG SDL2_VERSION=2.32.8

RUN apt-get update && \
    apt-get install -y wget unzip g++-mingw-w64-x86-64 && \
    wget -q https://github.com/libsdl-org/SDL/releases/download/release-${SDL2_VERSION}/SDL2-devel-${SDL2_VERSION}-mingw.zip && \
    unzip SDL2-devel-${SDL2_VERSION}-mingw.zip && \
    cp -r SDL2-${SDL2_VERSION}/x86_64-w64-mingw32 /usr && \
    rm -rf SDL2-devel-${SDL2_VERSION}-mingw.zip SDL2-${SDL2_VERSION}

WORKDIR /app